//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CipherBox.Office.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CipherBox.Office.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot;
        ///   targetNamespace=&quot;http://schemas.microsoft.com/office/2006/keyEncryptor/password&quot;
        ///   xmlns=&quot;http://schemas.microsoft.com/office/2006/keyEncryptor/password&quot;
        ///   xmlns:e=&quot;http://schemas.microsoft.com/office/2006/encryption&quot;
        ///   xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;xs:import namespace=&quot;http://schemas.microsoft.com/office/2006/encryption&quot; schemaLocation=&quot;encryptionInfo.xsd&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AgilePasswordKeyEncryptor {
            get {
                return ResourceManager.GetString("AgilePasswordKeyEncryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot;
        ///   targetNamespace=&quot;http://schemas.microsoft.com/office/2006/encryption&quot;
        ///   xmlns=&quot;http://schemas.microsoft.com/office/2006/encryption&quot;
        ///   xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  
        ///  &lt;xs:simpleType name=&quot;ST_SaltSize&quot;&gt;
        ///    &lt;xs:restriction base=&quot;xs:unsignedInt&quot;&gt;
        ///      &lt;xs:minInclusive value=&quot;1&quot; /&gt;
        ///      &lt;xs:maxInclusive value=&quot;65536&quot; /&gt;
        ///    &lt;/xs:restriction&gt;
        ///  &lt;/xs:simpleType&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AgileXmlEncryptionDescriptor {
            get {
                return ResourceManager.GetString("AgileXmlEncryptionDescriptor", resourceCulture);
            }
        }
    }
}
